name: Android CI

on:
  workflow_dispatch:
    branches: [main]
  push:
    branches: [main]
    paths:
      - "app/src/**"
  pull_request:
    branches: [main]
    paths:
      - "app/src/**"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FIREBASE_SECRET: ${{ secrets.FIREBASE_SECRET }}
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: set up secrets
        run: echo $FIREBASE_SECRET > app/google-services.json
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
